### ISSUE TITLE
Merge Version 2 into Master

### ISSUE THREAD

**Issue by GilliusThunderHead** [H34l0r/IPProject#24]
We need to remove conflicting in the Master branch and merge Version 2 into Master

**Comment by H34l0r** [comment]
Completed via a lot of merging:

* Merged master into this branch
* Merged this branch into master (only locally)
* Merged master back into this branch
* Approved pull request #22, which merged this branch back into master

Probably a very silly way to do it, but it seems to have worked.

**Comment by GilliusThunderHead** [comment]
Thanks mate, as mentioned I should have the login page sorted by the end of the weekend. I've created a couple issues for Ben and Gary to have a look at and there are a couple more I still need to add.

Sent from my iPhone

On 28 Sep 2017, at 5:46 pm, H34l0r <notifications@github.com<mailto:notifications@github.com>> wrote:


Completed via a lot of merging:

  *   Merged master into this branch
  *   Merged this branch into master (only locally)
  *   Merged master back into this branch
  *   Approved pull request #22<https://github.com/H34l0r/IPProject/pull/22>, which merged this branch back into master

Probably a very silly way to do it, but it seems to have worked.
